server:
  port: 8080

spring:
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
  datasource:
    driver-class-name: org.postgresql.Driver
    password: admin
    username: admin
    url: jdbc:postgresql://localhost:5432/subscription
  jpa:
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    hibernate:
      ddl-auto: validate
    open-in-view: false