server:
  port: 8080

spring:
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
  datasource:
    driver-class-name: org.postgresql.Driver
    password: admin
    username: admin
    url: jdbc:postgresql://localhost:5432/registration
  jpa:
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    hibernate:
      ddl-auto: update
    open-in-view: false

logging:
  level:
    org.hibernate:
      SQL: debug
      orm.jdbc.bind: trace
      type.descriptor.sql: trace

axon:
  event-handling:
    processors:
      customer-group:
        mode: subscribing
  axonserver:
    servers: localhost:8124